# Generated by Django 4.2.5 on 2023-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
