# Generated by Django 4.2.5 on 2023-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pokemon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='thumbnail',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
